// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oznnxfrbrimslfwnwwpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96bm54ZnJicmltc2xmd253d3B1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NjEwNDIsImV4cCI6MjA3NzIzNzA0Mn0.olM9lPisNSBrwBt2_GV3cszSxQYcWnozqE1_Dr9bCDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
